### ISSUE TITLE
Azure DevOps CI/CD - Invalid YAML file in documentation

### ISSUE THREAD

**Issue by RudyCo** [dotnet/docs-aspire#541]
### Describe the issue or suggestion

The following task is invalid:
```
  - task: Install .NET Aspire workload
    inputs: 
        inlineScript: |
            dotnet workload install aspire
```
Error is:
```
/.azdo/pipelines/azure-dev.yml (Line: 22, Col: 11): Task reference must be in the format <NAME>@<MAJOR_VERSION> or <NAME>@<MAJOR_VERSION.MINOR_VERSION.PATCH_VERSION>. For example MyTask@2 or MyTask@2.3.1. The following task reference format is invalid: 'Install .NET Aspire workload'
```

Source: https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions?tabs=windows%2Cvisual-studio&pivots=azure-pipelines

Potential fix
```
  - task: Bash@3
    displayName: Install .NET Aspire workload
    inputs:
      targetType: 'inline'
      script: |
        dotnet workload install aspire
```
